### ISSUE TITLE
Computation is higher than VINS.

### ISSUE THREAD

**Issue by YiChenCityU** [MIT-SPARK/Kimera-VIO#102]
I  run the dataset of euroc on Kimera and VINS-fusion. I found that the computation load is very high. Is it contradict with gtsam's claim that gtsam is more efficient than ceres?

**Comment by ToniRV** [comment]
The reason why the load is high is rather because the parameters are set to get the most out of the typical compute power of a laptop. We will push a set of “lightweight” params soon.

In any case, I would not draw conclusions on whether gtsam or ceres runs faster by looking at Kimera vs VINS-Fusion load.

**Comment by YiChenCityU** [comment]
Thanks a lot. I know the frontend of VINS is very simple. Maybe this is also the reason.
