### ISSUE TITLE
Does Kimera-Vio can run test with other dataset such as Kitti or Oxford ? 

### ISSUE THREAD

**Issue by thanghv97** [MIT-SPARK/Kimera-VIO#130]
I want to test performance of Kimera-Vio with other dataset such as Kitti, but I only found script and binary for Euroc. How to run Kimera-Vio with other dataset? might be my dataset

**Comment by hellovuong** [comment]
As far as I know, Kimera-VIO deprecated Kitti datasets due to the lack of synchronized high-frequency IMU data in the synced datasets of Kitti. About your dataset, to run it on Kimera VIO, you have 2 option:
- make your own Dataprovider module 
- organize your datasets same as Euroc format and you can run it directly on Kimera-VIO
