### ISSUE TITLE
Rolling Shutter support for Kimera-VIO

### ISSUE THREAD

**Issue by ujasmandavia** [MIT-SPARK/Kimera-VIO#203]
Has one using Kimera-VIO tried using it for a Rolling Shutter camera or does have any idea of adding rolling shutter support to Kimera-VIO?

Thanks!

**Comment by marcusabate** [comment]
We did look into this, it's a nontrivial extension but the groundwork is there on the gtsam side. Given the time elapsed since posting I will assume this is no longer relevant, however feel free to reopen if you would like to pursue this. At this time we don't have any plans to implement it officially.
