### ISSUE TITLE
Any suggestions for tuning a larger scale (outdoor) environment 

### ISSUE THREAD

**Issue by notalltim** [MIT-SPARK/Kimera-VIO#39]
I am working with a data set collected from airsim (neighborhood environment shown below) Do you have any thoughts on optimizing for larger environments? 
![0477_front_right_img](https://user-images.githubusercontent.com/3758998/76538788-3c4f0c80-6456-11ea-92f5-e97475db17e1.png)

**Comment by ToniRV** [comment]
Hi @Timbama, looks nice!
Kimera-VIO itself is running a fixed-lag smoothing backend, so there should be no scalability issue for pose estimation. Pose-graph optimization might be a bit more tricky, but since it is running in another slower thread, it should not be a problem.
For metric-semantic reconstruction with [Kimera-Semantics](https://github.com/MIT-SPARK/Kimera-Semantics/tree/master), it scales fairly well, but there is no current mechanism developed to save the 3D reconstruction to disk to make it truly scalable to large-scale scenarios, it shouldn't be too difficult though).
